### ISSUE TITLE
cloud No function after aktivate collabo

### ISSUE THREAD

**Issue by sinus23** [sureshprakash/owncloud-collaboration#14]
after aktivate the app my cloud get an fail...

Symfony\Component\Routing\Exception\InvalidParameterException: Parameter "rel_path" for route "collaboration_route" must match "[^/]++" ("" given) to generate a corresponding URL.
/var/www/owncloud/3rdparty/symfony/routing/Symfony/Component/Routing/Generator/UrlGenerator.php - line 140: Symfony\Component\Routing\Generator\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'collaboration_r...', false, Array, Array)
/var/www/owncloud/lib/private/route/router.php - line 325: Symfony\Component\Routing\Generator\UrlGenerator->generate('collaboration_r...', Array, false)
/var/www/owncloud/lib/private/urlgenerator.php - line 65: OC\Route\Router->generate('collaboration_r...', Array)
/var/www/owncloud/lib/private/helper.php - line 66: OC\URLGenerator->linkToRoute('collaboration_r...', Array)
/var/www/owncloud/lib/public/util.php - line 301: OC_Helper linkToRoute('collaboration_r...', Array)
/var/www/owncloud/apps/collaboration/appinfo/app.php - line 28: OCP\Util linkToRoute('collaboration_r...', Array)
/var/www/owncloud/lib/private/app.php - line 160: require_once('/var/www/ownclo...')
/var/www/owncloud/lib/private/app.php - line 141: OC_App requireAppFile('collaboration')
/var/www/owncloud/lib/private/app.php - line 118: OC_App loadApp('collaboration')
/var/www/owncloud/lib/base.php - line 847: OC_App loadApps()
/var/www/owncloud/index.php - line 39: OC handleRequest()
{main}

You cant use the cloud with aktivate app, so if it disable all be fine
Owncloud 8.2.2
Operating system	Ubuntu Linux 14.04.1
Kernel and CPU	Linux 3.13.0-74-generic on x86_64
Processor information	Intel Xeon E312xx (Sandy Bridge), 4 cores

**Comment by sinus23** [comment]
so: other server based on fucking ubuntu, its work with oc8.2
so what???

**Comment by liska12** [comment]
I tried it on Debian and Owncloud 8.2 and I got this error after activating:
`
Exception: {"Exception":"Symfony\\Component\\Routing\\Exception\\InvalidParameterException","Message":"Parameter \"rel_path\" for route \"collaboration_route\" must match \"[^\/]++\" (\"\" given) to generate a corresponding URL.","Code":0,"Trace":"#0 \/var\/www\/owncloud6a\/3rdparty\/symfony\/routing\/Symfony\/Component\/Routing\/Generator\/UrlGenerator.php(140): Symfony\\Component\\Routing\\Generator\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'collaboration_r...', false, Array, Array)\n#1 \/var\/www\/owncloud6a\/lib\/private\/route\/router.php(314): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('collaboration_r...', Array, false)\n#2 \/var\/www\/owncloud6a\/lib\/private\/urlgenerator.php(65): OC\\Route\\Router->generate('collaboration_r...', Array)\n#3 \/var\/www\/owncloud6a\/lib\/private\/helper.php(66): OC\\URLGenerator->linkToRoute('collaboration_r...', Array)\n#4 \/var\/www\/owncloud6a\/lib\/public\/util.php(301): OC_Helper::linkToRoute('collaboration_r...', Array)\n#5 \/var\/www\/owncloud6a\/apps\/collaboration\/appinfo\/app.php(28): OCP\\Util::linkToRoute('collaboration_r...', Array)\n#6 \/var\/www\/owncloud6a\/lib\/private\/app.php(160): require_once('\/var\/www\/ownclo...')\n#7 \/var\/www\/owncloud6a\/lib\/private\/app.php(141): OC_App::requireAppFile('collaboration')\n#8 \/var\/www\/owncloud6a\/lib\/private\/app.php(118): OC_App::loadApp('collaboration')\n#9 \/var\/www\/owncloud6a\/lib\/base.php(815): OC_App::loadApps()\n#10 \/var\/www\/owncloud6a\/index.php(39): OC::handleRequest()\n#11 {main}","File":"\/var\/www\/owncloud6a\/3rdparty\/symfony\/routing\/Symfony\/Component\/Routing\/Generator\/UrlGenerator.php","Line":167
`
